USE WeblinksInterconnectDB;

DELIMITER ;;
DROP PROCEDURE IF EXISTS `sp_UpdateAggResult`;;
CREATE PROCEDURE `sp_UpdateAggResult`(
IN IN_PARTNER VARCHAR(24),
IN IN_BILLING_MONTH VARCHAR(24),
IN IN_SCENARIO VARCHAR(24),
IN IN_CDR_COUNT INT,
IN IN_SECOND_COUNT INT,
IN IN_COST double
)
BEGIN
DECLARE rowExist int;
DECLARE currentBal,newBal double;
DECLARE currentCount,newCount int;
select count(*) from INTERCONNECT_BILLING_RESULTS where PARTNER = IN_PARTNER and SCENARIO=IN_SCENARIO and BILLING_MONTH=IN_BILLING_MONTH into rowExist;
If rowExist=0 then
INSERT INTO INTERCONNECT_BILLING_RESULTS (PARTNER,SCENARIO,BILLING_MONTH,CDR_COUNT,SECOND_COUNT,COST) VALUES (IN_PARTNER,IN_SCENARIO,IN_BILLING_MONTH,IN_CDR_COUNT,IN_SECOND_COUNT,IN_COST);
else
select CDR_COUNT from INTERCONNECT_BILLING_RESULTS where PARTNER = IN_PARTNER and SCENARIO=IN_SCENARIO and BILLING_MONTH=IN_BILLING_MONTH into currentCount;
set newCount = currentCount + IN_CDR_COUNT;
update INTERCONNECT_BILLING_RESULTS set CDR_COUNT = newCount where PARTNER = IN_PARTNER and SCENARIO=IN_SCENARIO and BILLING_MONTH=IN_BILLING_MONTH;
select SECOND_COUNT from INTERCONNECT_BILLING_RESULTS where PARTNER = IN_PARTNER and SCENARIO=IN_SCENARIO and BILLING_MONTH=IN_BILLING_MONTH into currentCount;
set newCount = currentCount + IN_SECOND_COUNT;
update INTERCONNECT_BILLING_RESULTS set SECOND_COUNT = newCount where PARTNER = IN_PARTNER and SCENARIO=IN_SCENARIO and BILLING_MONTH=IN_BILLING_MONTH;
select COST from INTERCONNECT_BILLING_RESULTS where PARTNER = IN_PARTNER and SCENARIO=IN_SCENARIO and BILLING_MONTH=IN_BILLING_MONTH into currentBal;
set newBal = currentBal + IN_COST;
update INTERCONNECT_BILLING_RESULTS set COST = newBal where PARTNER = IN_PARTNER and SCENARIO=IN_SCENARIO and BILLING_MONTH=IN_BILLING_MONTH;
end if;
END;;
DELIMITER ;
